apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-version1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
      version: "1"
  template:
    metadata:
      labels:
        app: nodeapp
        version: "1"
    spec:
      containers:
      - name: nodeappv1-container
        image: dusrbpoiiij/canarynodeapp:0.1
        ports:
        - containerPort: 3000
